default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: clearmyspam_development
  url: <%= ENV["CLEARMYSPAM_DATABASE_URL_DEVELOPMENT"] %>
test:
  <<: *default
  database: clearmyspam_test
  url: <%= ENV["CLEARMYSPAM_DATABASE_URL_TEST"] %>

production:
  <<: *default
  database: clearmyspam_production
  username: clearmyspam
  password: <%= ENV["CLEARMYSPAM_DATABASE_PASSWORD"] %>
